// 推荐种子数据：平台 / 分类 / 剧名 / 主役CV / 原著 / 剧情简介
export interface RecommendationSeed {
  title: string;
  platform: 'missevan' | 'manbo';
  category: 'audio_drama' | 'audiobook';
  voiceActors: string;
  originalWork: string;
  synopsis: string;
  coverUrl?: string;
}

export const recommendationSeeds: RecommendationSeed[] = [
  // --- 猫耳-广播剧 ---
  {
    title: '魔道祖师',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '路知行（魏无羡）× 魏超（蓝忘机）',
    originalWork: '墨香铜臭',
    synopsis: '玄幻仙侠：前世家主魏无羡死后重生，与含光君蓝忘机重逢，携手追查陈年诡案、守护天下苍生。',
  },
  {
    title: '撒野',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '倒霉死勒（蒋丞）× 涅槃（顾飞）',
    originalWork: '巫哲',
    synopsis: '校园成长：两个少年在钢厂小城里互相救赎、彼此成全的双向奔赴。',
  },
  {
    title: '默读',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '杨天翔（费渡）× 刘琮（骆闻舟）',
    originalWork: 'Priest',
    synopsis: '刑侦悬疑：在连环命案背后，费渡与骆闻舟联手剥开层层黑暗真相。',
  },
  {
    title: '杀破狼',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '阿杰（顾昀）× 杨天翔（长庚）',
    originalWork: 'Priest',
    synopsis: '权谋机甲：乱世大梁，长庚与顾昀权谋相携、共守家国。',
  },
  {
    title: '天官赐福',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '苏尚卿（谢怜）× 陈张太康（花城）',
    originalWork: '墨香铜臭',
    synopsis: '玄幻：仙乐太子谢怜三次飞升，与绝境鬼王花城相遇相守。',
  },
  {
    title: '将进酒',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '姜广涛（沈兰舟）× 袁铭喆（萧驰野）',
    originalWork: '唐酒卿',
    synopsis: '古风权谋：乱世争霸，中博王萧驰野与沈兰舟结盟问鼎天下。',
  },
  {
    title: '针锋对决',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '绿竹（顾青裴）× 逆鳞无伤（原炀）',
    originalWork: '水千丞',
    synopsis: '现代：高冷总裁与兵痞少爷明争暗斗、针锋相对的相爱相杀。',
  },
  {
    title: '小蘑菇',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '孙路路（安折）× 阿杰（陆沨）',
    originalWork: '一十四洲',
    synopsis: '末世科幻：地磁消失、异种入侵，小蘑菇安折与审判官陆沨的末世之恋。',
  },
  {
    title: '吞海',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '郑希（步重华）× 陈张太康（吴雩）',
    originalWork: '淮上',
    synopsis: '缉毒刑侦：跨国贩毒暗网大案，步重华与吴雩在黑暗中彼此救赎。',
  },
  {
    title: '二哈和他的白猫师尊',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '商桐（墨燃）× 卡修（楚晚宁）',
    originalWork: '肉包不吃肉',
    synopsis: '仙侠：墨燃重生悔悟，救赎如白猫般的师尊楚晚宁。',
  },
  {
    title: '奇洛李维斯回信',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '陈张太康（赵声阁）× 郑希（陈挽）',
    originalWork: '清明谷雨',
    synopsis: '现代暗恋：暗恋与回应的双向奔赴。',
  },
  {
    title: '偷偷藏不住',
    platform: 'missevan',
    category: 'audio_drama',
    voiceActors: '浮梦若薇（桑稚）× 轩ZONE（段嘉许）',
    originalWork: '竹已',
    synopsis: '现代言情：她是段嘉许无法言说的心事，也是他珍藏的宝藏。',
  },

  // --- 猫耳-有声剧 ---
  {
    title: '三体（全六季）',
    platform: 'missevan',
    category: 'audiobook',
    voiceActors: '729声工场制作',
    originalWork: '刘慈欣',
    synopsis: '科幻史诗：地球文明与三体文明跨越星海的对抗与黑暗森林法则。',
  },
  {
    title: '鬼吹灯系列',
    platform: 'missevan',
    category: 'audiobook',
    voiceActors: '青雪演播',
    originalWork: '天下霸唱',
    synopsis: '悬疑盗墓：摸金校尉深入古墓、机关暗器与奇闻异事的惊险旅程。',
  },
  {
    title: '二哈和他的白猫师尊（有声剧）',
    platform: 'missevan',
    category: 'audiobook',
    voiceActors: '谷江山（墨燃）× 三石（楚晚宁）',
    originalWork: '肉包不吃肉',
    synopsis: '仙侠：师徒之间跨越前世的救赎与守护。',
  },
  {
    title: '门生故旧',
    platform: 'missevan',
    category: 'audiobook',
    voiceActors: '陈张太康等',
    originalWork: '',
    synopsis: '现代情感悬疑：沈衍名与季誉之间纠缠多年的过往与秘密。',
  },
  {
    title: '初三的六一儿童节',
    platform: 'missevan',
    category: 'audiobook',
    voiceActors: '蛇蝎点点',
    originalWork: '',
    synopsis: '热血救赎：热血、精英、强强碰撞的群像故事。',
  },
  {
    title: '理想型',
    platform: 'missevan',
    category: 'audiobook',
    voiceActors: '苏尚卿、凌飞等',
    originalWork: 'Snoofy',
    synopsis: '现代恋爱：关于理想型与现实的心动日常。',
  },
  {
    title: '日出风来',
    platform: 'missevan',
    category: 'audiobook',
    voiceActors: '云惟一（沈风来）× 马正阳（林出）',
    originalWork: '春日夏禾',
    synopsis: '现代：逐光而行的双向奔赴。',
  },
  {
    title: '尾钩',
    platform: 'missevan',
    category: 'audiobook',
    voiceActors: '左岸',
    originalWork: '',
    synopsis: '现代：猫耳FM、野声文化联合出品的付费有声剧。',
  },
  {
    title: '不良执念清除师',
    platform: 'missevan',
    category: 'audiobook',
    voiceActors: '蒲一永主役',
    originalWork: '',
    synopsis: '现代灵异治愈：能看见执念的少年替人解开心结的故事。',
  },

  // --- 漫播-广播剧 ---
  {
    title: '人鱼陷落',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '张福正（白楚年）× 马正阳（兰波）',
    originalWork: '麟潜',
    synopsis: 'ABO末世：变异生物横行的末世，白楚年与最强人鱼兰波相爱相杀、彼此守护。',
  },
  {
    title: '靡言',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '文森（摩川）× 金弦（柏胤）',
    originalWork: '回南雀',
    synopsis: '民俗都市：清冷神性的摩川与珠宝设计师柏胤的宿命纠葛。',
  },
  {
    title: '皇恩浩荡',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '史泽鲲（贺怀翎）× 刘思岑（祝云璟）',
    originalWork: '白芥子',
    synopsis: '古风甜宠：淮安侯世子与皇太子之间宠溺与守护的日常。',
  },
  {
    title: '江山许你',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '赵毅（梁祯）× 羊仔（祝云瑄）',
    originalWork: '',
    synopsis: '古风权谋：漫播人气会员剧。',
  },
  {
    title: '星期天的病人',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '文森 × 刘思岑',
    originalWork: '',
    synopsis: '现代：少年音与美人音碰撞的禁忌心动。',
  },
  {
    title: 'Endless Echoes（欲言难止）',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '史泽鲲（陆赫扬）× 胡良伟（许则）',
    originalWork: '麦香鸡呢',
    synopsis: '双A暗恋、破镜重圆。',
  },
  {
    title: '这位alpha身残志坚',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '三碗过岗',
    originalWork: '',
    synopsis: 'ABO末世：第一军团少将白历的身残志坚传奇。',
  },
  {
    title: '安慰剂效应',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '咸鱼定理',
    originalWork: '',
    synopsis: '漫播与729声工场联合出品，现代。',
  },
  {
    title: '提灯映桃花',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '',
    originalWork: '淮上',
    synopsis: '神魔：上古战场，凤凰明王与大魔之恋。',
  },
  {
    title: '大珰',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '',
    originalWork: '童子',
    synopsis: '古风权谋：宦官群像与庙堂风云。',
  },
  {
    title: '壹号身份管理局',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '',
    originalWork: '',
    synopsis: '科幻单元剧：共19集包含7个单元短剧，漫播会员剧。',
  },
  {
    title: '相欺',
    platform: 'manbo',
    category: 'audio_drama',
    voiceActors: '',
    originalWork: '',
    synopsis: '现代情感：漫播独家播出。',
  },

  // --- 漫播-有声剧 ---
  {
    title: '囚于永夜',
    platform: 'manbo',
    category: 'audiobook',
    voiceActors: '张福正（顾昀迟）× 孙路路（温然）',
    originalWork: '麦香鸡呢',
    synopsis: 'ABO先婚后爱：温然被植入腺体后与高匹配度Alpha顾昀迟的双向救赎。',
  },
  {
    title: '小潭山没有天文台',
    platform: 'manbo',
    category: 'audiobook',
    voiceActors: '史泽鲲（谭又明）× 徐宇隆（沈宗年）',
    originalWork: '',
    synopsis: '现代：爱里长大的小太阳与阴郁腹黑少年的暗恋守候。',
  },
  {
    title: '欲言难止（有声剧）',
    platform: 'manbo',
    category: 'audiobook',
    voiceActors: '顺子 × 倒霉死勒',
    originalWork: '麦香鸡呢',
    synopsis: '双A酸涩暗恋、破镜重圆。',
  },
  {
    title: '奇洛李维斯回信（有声剧）',
    platform: 'manbo',
    category: 'audiobook',
    voiceActors: '徐宇隆（沈宗年）× 史泽鲲（谭又明）',
    originalWork: '清明谷雨',
    synopsis: '现代暗恋：与《小潭山没有天文台》同世界观的追爱故事。',
  },
  {
    title: '丙丁神通（有声剧）',
    platform: 'manbo',
    category: 'audiobook',
    voiceActors: '史泽鲲 × 孙路路',
    originalWork: '',
    synopsis: '漫播出品。',
  },
  {
    title: '区区（有声剧）',
    platform: 'manbo',
    category: 'audiobook',
    voiceActors: '孙睿扬 × 袁铭喆',
    originalWork: '',
    synopsis: '漫播出品。',
  },
  {
    title: '忏悔地（有声剧）',
    platform: 'manbo',
    category: 'audiobook',
    voiceActors: '袁铭喆 × 顺子',
    originalWork: '',
    synopsis: '漫播出品，共73集。',
  },
  {
    title: '少爷归家（广播短剧）',
    platform: 'manbo',
    category: 'audiobook',
    voiceActors: '',
    originalWork: '',
    synopsis: '漫播出品。',
  },
  {
    title: '二哈和他的白猫师尊（漫播有声剧）',
    platform: 'manbo',
    category: 'audiobook',
    voiceActors: '谷江山（墨燃）× 三石（楚晚宁）',
    originalWork: '肉包不吃肉',
    synopsis: '仙侠：猫耳、漫播均有上架。',
  },
];
